// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC29OZgESUnc6SpzxEF33UFEApb3nMt68M',
    appId: '1:278708748939:android:5bf5c9815f5307f1524a8e',
    messagingSenderId: '278708748939',
    projectId: 'e-money-a83f0',
    storageBucket: 'e-money-a83f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA46uBUvmVQKsSL7HIXZG58MD9jXQCFX7c',
    appId: '1:948878883710:ios:5363ad2b9fbe06b2a0512f',
    messagingSenderId: '948878883710',
    projectId: 'fir-emoney-e9256',
    storageBucket: 'fir-emoney-e9256.firebasestorage.app',
    iosBundleId: 'com.kampus.dompetKampusGlobal',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpnyImtcf0yWU7yYdJqm3jc19R-byYTV4',
    appId: '1:278708748939:web:6df81b560e7c5bc5524a8e',
    messagingSenderId: '278708748939',
    projectId: 'e-money-a83f0',
    authDomain: 'e-money-a83f0.firebaseapp.com',
    storageBucket: 'e-money-a83f0.firebasestorage.app',
    measurementId: 'G-LD54HKFCR5',
  );

}